import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="capstone project graduation design course design project selection requirement analysis user story feature list non-functional requirement technology selection architecture diagram module split database design API design permission design frontend page backend API full-stack data analysis AI application RAG mobile embedded DevOps Docker Nginx GitHub Actions test plan test case defect management README technical documentation project report defense material demo script demo video portfolio GitHub Profile project review project highlight technical difficulty performance optimization maintainability interview project presentation user research wireframe prototype system design design doc sprint backlog CI CD pipeline deployment monitoring logging error handling edge case load test stress test unit test integration test end-to-end test code review pair programming agile methodology scrum kanban retrospective MVP iterative development version control git branching strategy merge conflict resolution hotfix feature branch release branch semantic versioning changelog release notes project walkthrough architecture deep dive";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"cp-tag-"+String(i+1).padStart(3,"0"),name:n,category:"Capstone",description:"Cap标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"cp-course-01",order:1,slug:"Cap入门",title:"综合项目入门与毕业作品路线",description:"项目价值、课程定位、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"cp-course-02",order:2,slug:"需求分析",title:"项目选题、需求分析与用户场景",description:"选题方法、用户故事、需求文档。",estimatedHours:10,diff:"medium"},
  {id:"cp-course-03",order:3,slug:"技术选型",title:"技术选型、架构设计与模块拆分",description:"架构图、技术方案、模块划分。",estimatedHours:10,diff:"medium"},
  {id:"cp-course-04",order:4,slug:"前端项目",title:"前端项目实战与页面交互",description:"页面设计、组件开发、交互实现。",estimatedHours:10,diff:"medium"},
  {id:"cp-course-05",order:5,slug:"后端API",title:"后端API、数据库与权限设计",description:"API设计、数据建模、认证授权。",estimatedHours:10,diff:"hard"},
  {id:"cp-course-06",order:6,slug:"数据分析",title:"数据分析、可视化与报表项目",description:"数据处理、图表展示、报表输出。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-07",order:7,slug:"AI应用",title:"AI应用、RAG与智能助手项目",description:"AI集成、RAG架构、智能助手。",estimatedHours:10,diff:"hard"},
  {id:"cp-course-08",order:8,slug:"DevOps部署",title:"DevOps、Docker、Nginx与部署上线",description:"容器化、CI/CD、域名、部署。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-09",order:9,slug:"测试质量",title:"测试、质量保障与缺陷管理",description:"测试计划、用例、缺陷流程。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-10",order:10,slug:"项目文档",title:"项目文档、README与技术报告",description:"文档结构、README、技术报告。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-11",order:11,slug:"演示答辩",title:"演示视频、答辩PPT与讲解脚本",description:"演示脚本、PPT设计、答辩准备。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-12",order:12,slug:"作品集包装",title:"GitHub作品集、个人主页与项目包装",description:"作品集展示、项目亮点、效果图。",estimatedHours:8,diff:"hard"},
  {id:"cp-course-13",order:13,slug:"项目案例",title:"毕业设计、课程设计与求职项目案例",description:"多种方向的项目案例与复盘。",estimatedHours:10,diff:"hard"},
  {id:"cp-course-14",order:14,slug:"项目复盘",title:"综合项目复盘、迭代与作品集完善",description:"复盘方法、迭代改进、作品完善。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["能完成综合项目","会文档和演示","能做作品集","能讲项目"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"cp-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["Capstone"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"Cap课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["综合项目","完整交付"],["毕业设计","结业项目"],["需求分析","需求定义"],["技术选型","技术决策"],["架构设计","系统结构"],["全栈项目","前后端"],["AI项目","智能应用"],["DevOps","部署运维"],["测试","质量保障"],["项目文档","技术文档"],["答辩","演示"],["作品集","展示"],["代码评审","质量检查"],["敏捷开发","迭代"],["部署上线","发布"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"cp-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"Capstone",tags:["Capstone"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"cp-kp-"+String(k.length+1).padStart(4,"0"),name:"Cap概念"+(k.length+1),description:"Cap概念",category:"Capstone",tags:["Capstone"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["Cap入门","需求分析","技术选型","前端项目","后端API","数据分析","AI应用","DevOps部署","测试质量","项目文档","演示答辩","作品集包装","项目案例","项目复盘"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"综合项目第一步？",["项目选题","写代码","部署","测试"],"A","easy"],[1,"用户故事格式？",["As a/ I want/ So that","标题/内容","需求/方案","功能/界面"],"A","easy"],[2,"技术选型依据？",["需求/团队/生态","最热门","最新","最贵"],"A","medium"],[3,"架构图重要性？",["展示系统结构和模块关系","装饰文档","替代代码","展示UI"],"A","medium"],[4,"RESTful API设计原则？",["资源URL+HTTP方法","使用动词","使用GET所有","无规范"],"A","medium"],[5,"Docker作用？",["容器化部署环境","写代码","做UI","管理数据"],"A","medium"],[6,"CI/CD管道目标？",["自动化构建测试部署","手动部署","定期备份","代码审查"],"A","hard"],[7,"项目文档核心？",["需求/设计/部署/使用","代码注释","开发日志","团队规范"],"A","hard"],[9,"演示答辩重点？",["问题和方案","代码量","技术细节","页面数量"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"cp-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:600},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:800},{type:"case_analysis",min:1600}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="cp-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于项目"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="项目"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是项目开发的重要环节。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="项目"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在项目开发中的作用。";o=[{label:"A",text:"简答"}];a=ch+"很重要。";}
    else if(it.type==="case_analysis"){s="项目"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"cp-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["学习平台","在线考试","个人知识库","博客系统","Todo应用","图书管理","电商后台","校园二手","课程表","AI问答","RAG知识库","数据分析看板","求职作品集","记账App","环境监测","Docker部署","毕设答辩","项目面试"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"cp-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握项目开发",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"需求",description:"分析"},{order:2,title:"设计",description:"方案"},{order:3,title:"实现",description:"编码"},{order:4,title:"交付",description:"部署"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"Cap路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"cp-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["综合项目","毕业设计","技术选型","架构设计","Docker","CI/CD","全栈","测试","文档","答辩","作品集","需求分析","API设计","敏捷","DevOps"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["Cap概念"+i,"Cap概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"cp-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"Capstone",tags:["Capstone"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["项目问题"+(i+1)+"?","项目问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"cp-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"Capstone",tags:["Capstone"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["Capstone"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["Capstone"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["Capstone"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["Capstone"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["Capstone"]});});return e;}
async function main(){
  console.log("Gen Capstone...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-capstone-projects",slug:"module-capstone-projects",title:"综合项目实战与毕业作品",subtitle:"面向综合项目实践者",description:"面向综合项目学习者的项目选题需求分析技术选型架构设计前后端实现AI应用测试部署文档写作作品集包装与毕业设计交付训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["综合项目","毕业设计","课程设计","作品集","项目实战","技术选型","部署上线","项目答辩"],estimatedHours:200,difficulty:"advanced",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F3ED}",repoUrl:"https://github.com/openskill-galaxy/module-capstone-projects",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
